### PR TITLE
Add d2k mod and Remove SC placeholder music folder

### PR DESCRIPTION
**Pull request by cookgreen**

### CODE REVIEW

**Review by yaaaaa — CHANGES_REQUESTED** [review]
-#SC
-zerg1: zerg1
-	Extension: wav
-zerg2: zerg2
-	Extension: wav
-zerg3: zerg3
-	Extension: wav
-terran1: terran1
-	Extension: wav
-terran2: terran2
-	Extension: wav
-terran3: terran3
-	Extension: wav
-protoss1: protoss1
-	Extension: wav
-protoss2: protoss2
-	Extension: wav
-protoss3: protoss3
-	Extension: wav

**Comment by yaaaaa** [comment]
and we do not need mix file

**Comment by cookgreen** [comment]
> -#SC
> -zerg1: zerg1
> 
> * Extension: wav
>   -zerg2: zerg2
> * Extension: wav
>   -zerg3: zerg3
> * Extension: wav
>   -terran1: terran1
> * Extension: wav
>   -terran2: terran2
> * Extension: wav
>   -terran3: terran3
> * Extension: wav
>   -protoss1: protoss1
> * Extension: wav
>   -protoss2: protoss2
> * Extension: wav
>   -protoss3: protoss3
> * Extension: wav

What does it mean?

**Comment by cookgreen** [comment]
> and we do not need mix file

And deleted

**Comment by yaaaaa** [comment]
in the music.yaml this must be deleted, we do not need use SC original assets

**Comment by cookgreen** [comment]
done @yaaaaa

**Pull request merged**
