### PR TITLE
Fix png load error

### PR DESCRIPTION
**Pull request by cookgreen**

### CODE REVIEW

**Comment by yaaaaa** [comment]
Needs to Delete Defaults trait
`drone:
	stand: 
		Combine:`
And will be fine.

**Comment by cookgreen** [comment]
@yaaaaa okay

**Review by yaaaaa — APPROVED** [review]

**Comment by yaaaaa** [comment]
We do not need remove defaults from all units, it needed to remove if unit have combine+default only

**Comment by cookgreen** [comment]
@yaaaaa gotcha

**Review by yaaaaa — APPROVED** [review]

**Pull request merged**
